version: "3.8"

services:
  transmission:
    container_name: Transmission
    image: linuxserver/transmission:4.0.4
    restart: always
    volumes:
      - ./config:/config
      - ../medias:/downloads
      - ./watch:/watch
    env_file:
      - .env
    ports:
      - "127.0.0.1:9091:9091"
