version: '3'
services:
  nginx:
    container_name: "NginxProxyManager"
    image: jc21/nginx-proxy-manager:2.10.4
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: always
    network_mode: "host"
    depends_on: 
      - npm_db

  npm_db:
    container_name: "NginxProxyManagerDB"
    image: jc21/mariadb-aria:latest
    env_file:
      - .env
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
